import { createReadStream } from 'node:fs';
import { mkdir, stat, unlink, writeFile } from 'node:fs/promises';
import { dirname, join, resolve, sep } from 'node:path';
import { Readable } from 'node:stream';

import {
  DeleteObjectCommand, GetObjectCommand, PutObjectCommand, S3Client,
} from '@aws-sdk/client-s3';

/**
 * Where complaint photo bytes live. Two drivers, one chosen at startup
 * (see `photoStoreFromEnv`):
 *
 *   disk  files under UPLOAD_DIR (the original behaviour);
 *   r2    objects in a Cloudflare R2 bucket, over the S3 API.
 *
 * Both are addressed by the same storage key the database row carries,
 * `complaints/<yyyy>/<reference>/<stage>-<n>.<ext>` (older rows:
 * `complaints/<yyyy>/<mm>/<uuid>.<ext>`). The disk path is that key under
 * UPLOAD_DIR; the R2 object key is that key with its `complaints/` head
 * swapped for R2_PREFIX (default `complaints/`, so the same). Nothing
 * here knows about HTTP; photo-storage.ts turns failures into the
 * sentences a person reads.
 */

export interface OpenedPhoto {
  stream: Readable;
  /** Bytes, when the store knows them up front (it always does today). */
  bytes: number | undefined;
}

export interface PhotoStore {
  /** For the one startup log line. Never carries a secret. */
  readonly description: string;
  /** The 404 sentence when a row's bytes are gone. */
  readonly missingMessage: string;
  put(storageKey: string, body: Buffer, contentType: string): Promise<void>;
  /** Null when there is no such photo. Any other failure throws. */
  get(storageKey: string): Promise<OpenedPhoto | null>;
  /** Removing a photo that is already gone is not an error. */
  remove(storageKey: string): Promise<void>;
}

const KEY_HEAD = 'complaints/';

/**
 * Keys are generated by the server, so anything else is a bug or a
 * tampered row. Refused before it reaches a path or a bucket.
 */
function assertKey(storageKey: string): void {
  if (
    !storageKey.startsWith(KEY_HEAD) ||
    !/^[A-Za-z0-9._/-]+$/.test(storageKey) ||
    storageKey.split('/').some((part) => part === '' || part === '.' || part === '..')
  ) {
    throw new Error(`Not a complaint photo storage key: ${storageKey}`);
  }
}

// ---------------------------------------------------------------------
// Disk
// ---------------------------------------------------------------------

/**
 * `||`, not `??`: an env file carrying `UPLOAD_DIR=` (blank) sets it to
 * "", and resolve("") is the working directory itself — photos would be
 * written loose into the app folder. Blank means unset.
 */
export function uploadRoot(): string {
  return resolve(process.env.UPLOAD_DIR?.trim() || join(process.cwd(), 'uploads'));
}

export class DiskPhotoStore implements PhotoStore {
  readonly description: string;
  readonly missingMessage =
    "That photo's file is missing on the server. Ask an admin to check the uploads folder.";

  constructor(private readonly root: string = uploadRoot()) {
    this.description = `local disk at ${root}`;
  }

  /** Resolves a stored key to its absolute path, refusing anything that escapes the root. */
  private pathFor(storageKey: string): string {
    assertKey(storageKey);
    const full = resolve(this.root, storageKey);
    if (!full.startsWith(this.root + sep)) {
      throw new Error(`Storage key escapes the upload directory: ${storageKey}`);
    }
    return full;
  }

  async put(storageKey: string, body: Buffer): Promise<void> {
    const full = this.pathFor(storageKey);
    await mkdir(dirname(full), { recursive: true });
    await writeFile(full, body);
  }

  async get(storageKey: string): Promise<OpenedPhoto | null> {
    const full = this.pathFor(storageKey);
    let bytes: number;
    try {
      const info = await stat(full);
      if (!info.isFile()) return null;
      bytes = info.size;
    } catch {
      return null;
    }
    return { stream: createReadStream(full), bytes };
  }

  async remove(storageKey: string): Promise<void> {
    await unlink(this.pathFor(storageKey)).catch((error: NodeJS.ErrnoException) => {
      if (error.code !== 'ENOENT') throw error;
    });
  }
}

// ---------------------------------------------------------------------
// Cloudflare R2
// ---------------------------------------------------------------------

/**
 * Deadlines. Every outbound call has one (the rule pool.ts states for the
 * database). The upload runs inside the raise/resolve transaction, so a
 * hung R2 would otherwise hold that transaction open indefinitely.
 *
 *   connect      R2 not answering at all
 *   request      no response headers within this long
 *   socket idle  a stalled body, either way; also frees a photo download
 *                whose browser went away mid-stream
 *   overall      put/delete, all attempts together. Not used on get: an
 *                overall cap would cut a slow phone off mid-photo, and
 *                the idle cap already bounds a stalled download.
 */
export const R2_TIMEOUTS = {
  connectMs: 5_000,
  requestMs: 20_000,
  socketIdleMs: 30_000,
  overallMs: 30_000,
};

/** The one method of S3Client the driver calls, so a test can stub it. */
export interface S3Sender {
  send: S3Client['send'];
}

function isNotFound(error: unknown): boolean {
  const e = error as { name?: string; $metadata?: { httpStatusCode?: number } } | null;
  return (
    e?.name === 'NoSuchKey' ||
    e?.name === 'NotFound' ||
    e?.$metadata?.httpStatusCode === 404
  );
}

export class R2PhotoStore implements PhotoStore {
  readonly description: string;
  readonly missingMessage = 'That photo is no longer available.';

  /**
   * @param prefix replaces the `complaints/` head of a storage key, so
   *   with the default prefix the object key IS the storage key.
   * @param legacy read-only fallback for photos written to disk before
   *   R2 was switched on. Never written to, never deleted from.
   */
  constructor(
    private readonly client: S3Sender,
    private readonly bucket: string,
    private readonly prefix: string,
    private readonly legacy: PhotoStore | null,
  ) {
    this.description =
      `Cloudflare R2, bucket "${bucket}", prefix "${prefix}"` +
      (legacy ? `; photos not in R2 are read from ${legacy.description}` : '');
  }

  objectKey(storageKey: string): string {
    assertKey(storageKey);
    return this.prefix + storageKey.slice(KEY_HEAD.length);
  }

  async put(storageKey: string, body: Buffer, contentType: string): Promise<void> {
    await this.client.send(
      new PutObjectCommand({
        Bucket: this.bucket,
        Key: this.objectKey(storageKey),
        Body: body,
        ContentType: contentType,
        ContentLength: body.length,
      }),
      { abortSignal: AbortSignal.timeout(R2_TIMEOUTS.overallMs) },
    );
  }

  async get(storageKey: string): Promise<OpenedPhoto | null> {
    try {
      const out = await this.client.send(
        new GetObjectCommand({ Bucket: this.bucket, Key: this.objectKey(storageKey) }),
      );
      const body = out.Body as unknown;
      if (!(body instanceof Readable)) {
        throw new Error(`R2 returned no readable body for ${storageKey}`);
      }
      return { stream: body, bytes: out.ContentLength };
    } catch (error) {
      if (!isNotFound(error)) throw error;
    }
    return this.legacy ? this.legacy.get(storageKey) : null;
  }

  async remove(storageKey: string): Promise<void> {
    // R2, like S3, answers 204 for a key that is not there.
    await this.client.send(
      new DeleteObjectCommand({ Bucket: this.bucket, Key: this.objectKey(storageKey) }),
      { abortSignal: AbortSignal.timeout(R2_TIMEOUTS.overallMs) },
    );
  }
}

// ---------------------------------------------------------------------
// Choosing one
// ---------------------------------------------------------------------

const R2_CREDENTIALS = ['R2_ACCOUNT_ID', 'R2_ACCESS_KEY_ID', 'R2_SECRET_ACCESS_KEY'] as const;

/** Blank means unset, as for UPLOAD_DIR. */
function env(source: NodeJS.ProcessEnv, name: string): string {
  return source[name]?.trim() ?? '';
}

/** `complaints/` → `complaints/`; `/prod/photos` → `prod/photos/`. */
function normalisePrefix(raw: string): string {
  const trimmed = raw.replace(/^\/+/, '').replace(/\/+$/, '');
  return trimmed ? `${trimmed}/` : KEY_HEAD;
}

/**
 * R2 when all three credentials are set, disk when none are. Some but not
 * all is a typo or a half-pasted env file; refusing to start says so now,
 * instead of quietly writing to a disk the deploy expects to be empty.
 */
export function photoStoreFromEnv(source: NodeJS.ProcessEnv = process.env): PhotoStore {
  const missing = R2_CREDENTIALS.filter((name) => !env(source, name));
  if (missing.length === R2_CREDENTIALS.length) return new DiskPhotoStore();
  if (missing.length > 0) {
    throw new Error(
      `Cloudflare R2 photo storage is only partly configured: ${missing.join(' and ')} ` +
        `${missing.length === 1 ? 'is' : 'are'} blank. Set all three of ` +
        `${R2_CREDENTIALS.join(', ')} to keep complaint photos in R2, or blank all three ` +
        `to keep them on local disk.`,
    );
  }

  const accountId = env(source, 'R2_ACCOUNT_ID');
  const client = new S3Client({
    region: 'auto',
    endpoint: env(source, 'R2_ENDPOINT') || `https://${accountId}.r2.cloudflarestorage.com`,
    credentials: {
      accessKeyId: env(source, 'R2_ACCESS_KEY_ID'),
      secretAccessKey: env(source, 'R2_SECRET_ACCESS_KEY'),
    },
    // R2 accepts both URL styles; path style keeps working with a custom
    // R2_ENDPOINT (e.g. a jurisdiction endpoint) and any bucket name.
    forcePathStyle: true,
    // Newer SDKs add CRC checksums to every upload by default; Cloudflare's
    // own guidance is to send them only where the API requires them.
    requestChecksumCalculation: 'WHEN_REQUIRED',
    responseChecksumValidation: 'WHEN_REQUIRED',
    maxAttempts: 2,
    requestHandler: {
      connectionTimeout: R2_TIMEOUTS.connectMs,
      requestTimeout: R2_TIMEOUTS.requestMs,
      throwOnRequestTimeout: true,
      socketTimeout: R2_TIMEOUTS.socketIdleMs,
    },
  });

  return new R2PhotoStore(
    client,
    env(source, 'R2_BUCKET') || 'sadbhavna',
    normalisePrefix(env(source, 'R2_PREFIX')),
    new DiskPhotoStore(),
  );
}
