/**
 * GENERATED by `npm run access:keys` in backend/, from
 * backend/src/access/catalogue. DO NOT EDIT BY HAND: edit the catalogue
 * and run the script again. `npm run access:keys -- --check` fails when
 * this file is stale (access plan 9.1, A6).
 *
 * GET /auth/me carries only keys and scopes (R3). Everything a screen
 * says about a key, its label above all, comes from here.
 */

/** Stored scope values (R1). `units` is labelled "Selected sites" on screen. */
export type Scope = 'own' | 'team' | 'units' | 'all'

export const SCOPES: readonly Scope[] = ['own', 'team', 'units', 'all']

/** Every permission key, three parts each: module.section.action. */
export type PermissionKey =
  | 'budget.projects.view'
  | 'budget.projects.create'
  | 'budget.projects.edit'
  | 'budget.projects.delete'
  | 'budget.projects.pick'
  | 'budget.sites.view'
  | 'budget.sites.create'
  | 'budget.sites.edit'
  | 'budget.sites.change_people'
  | 'budget.sites.delete'
  | 'budget.sites.pick'
  | 'budget.budgets.view'
  | 'budget.budgets.edit'
  | 'budget.expenses.view'
  | 'budget.expenses.create'
  | 'budget.expenses.edit'
  | 'budget.expenses.delete'
  | 'budget.cost_heads.manage'
  | 'budget.cost_heads.pick'
  | 'budget.reports.view'
  | 'budget.amounts.see'
  | 'complaints.complaints.view'
  | 'complaints.complaints.raise'
  | 'complaints.complaints.comment'
  | 'complaints.complaints.work'
  | 'complaints.complaints.approve'
  | 'complaints.complaints.reassign'
  | 'complaints.categories.manage'
  | 'complaints.categories.pick'
  | 'platform.people.view'
  | 'platform.people.create'
  | 'platform.people.edit'
  | 'platform.people.delete'
  | 'platform.people.pick'
  | 'platform.designations.manage'
  | 'platform.designations.pick'
  | 'platform.locations.manage'
  | 'platform.locations.pick'
  | 'access.rights.manage'

export const PERMISSION_KEYS: readonly PermissionKey[] = [
  'budget.projects.view',
  'budget.projects.create',
  'budget.projects.edit',
  'budget.projects.delete',
  'budget.projects.pick',
  'budget.sites.view',
  'budget.sites.create',
  'budget.sites.edit',
  'budget.sites.change_people',
  'budget.sites.delete',
  'budget.sites.pick',
  'budget.budgets.view',
  'budget.budgets.edit',
  'budget.expenses.view',
  'budget.expenses.create',
  'budget.expenses.edit',
  'budget.expenses.delete',
  'budget.cost_heads.manage',
  'budget.cost_heads.pick',
  'budget.reports.view',
  'budget.amounts.see',
  'complaints.complaints.view',
  'complaints.complaints.raise',
  'complaints.complaints.comment',
  'complaints.complaints.work',
  'complaints.complaints.approve',
  'complaints.complaints.reassign',
  'complaints.categories.manage',
  'complaints.categories.pick',
  'platform.people.view',
  'platform.people.create',
  'platform.people.edit',
  'platform.people.delete',
  'platform.people.pick',
  'platform.designations.manage',
  'platform.designations.pick',
  'platform.locations.manage',
  'platform.locations.pick',
  'access.rights.manage',
]

/**
 * Each key's label: the words reasonFor builds its sentence from,
 * "Only people allowed to <label> can do this." (kit 26.2).
 */
export const PERMISSION_LABELS: Readonly<Record<PermissionKey, string>> = {
  'budget.projects.view': 'view projects',
  'budget.projects.create': 'add projects',
  'budget.projects.edit': 'edit projects',
  'budget.projects.delete': 'delete projects',
  'budget.projects.pick': 'pick projects',
  'budget.sites.view': 'view sites',
  'budget.sites.create': 'add sites',
  'budget.sites.edit': 'edit sites',
  'budget.sites.change_people': 'change a site\'s manager or supervisor',
  'budget.sites.delete': 'delete sites',
  'budget.sites.pick': 'pick sites',
  'budget.budgets.view': 'view budgets',
  'budget.budgets.edit': 'edit budgets',
  'budget.expenses.view': 'view expenses',
  'budget.expenses.create': 'add expenses',
  'budget.expenses.edit': 'edit expenses',
  'budget.expenses.delete': 'delete expenses',
  'budget.cost_heads.manage': 'manage cost heads',
  'budget.cost_heads.pick': 'pick cost heads',
  'budget.reports.view': 'view reports',
  'budget.amounts.see': 'see amounts (cost, budgets)',
  'complaints.complaints.view': 'view complaints',
  'complaints.complaints.raise': 'raise complaints',
  'complaints.complaints.comment': 'comment on complaints',
  'complaints.complaints.work': 'start and resolve complaints assigned to them',
  'complaints.complaints.approve': 'approve or send back complaints',
  'complaints.complaints.reassign': 'reassign complaints',
  'complaints.categories.manage': 'manage complaint categories',
  'complaints.categories.pick': 'pick categories',
  'platform.people.view': 'view people',
  'platform.people.create': 'add people',
  'platform.people.edit': 'edit people',
  'platform.people.delete': 'delete people',
  'platform.people.pick': 'pick people',
  'platform.designations.manage': 'manage designations',
  'platform.designations.pick': 'pick designations',
  'platform.locations.manage': 'manage locations',
  'platform.locations.pick': 'pick locations',
  'access.rights.manage': 'manage roles and people\'s access',
}

export type ModuleKey = 'budget' | 'complaints' | 'platform' | 'access'

/** Each module's keys other than Picks. A module shows when the user holds any of them. */
export const MODULE_KEYS: Readonly<Record<ModuleKey, readonly PermissionKey[]>> = {
  budget: [
    'budget.projects.view',
    'budget.projects.create',
    'budget.projects.edit',
    'budget.projects.delete',
    'budget.sites.view',
    'budget.sites.create',
    'budget.sites.edit',
    'budget.sites.change_people',
    'budget.sites.delete',
    'budget.budgets.view',
    'budget.budgets.edit',
    'budget.expenses.view',
    'budget.expenses.create',
    'budget.expenses.edit',
    'budget.expenses.delete',
    'budget.cost_heads.manage',
    'budget.reports.view',
    'budget.amounts.see',
  ],
  complaints: [
    'complaints.complaints.view',
    'complaints.complaints.raise',
    'complaints.complaints.comment',
    'complaints.complaints.work',
    'complaints.complaints.approve',
    'complaints.complaints.reassign',
    'complaints.categories.manage',
  ],
  platform: [
    'platform.people.view',
    'platform.people.create',
    'platform.people.edit',
    'platform.people.delete',
    'platform.designations.manage',
    'platform.locations.manage',
  ],
  access: ['access.rights.manage'],
}

/** A Pick the action needs, at the needing permission's scope ('same') or a fixed one. */
export type CatalogueNeed =
  | { readonly pick: PermissionKey; readonly scope: 'same' | 'all' }
  | { readonly amounts: PermissionKey }

export interface CatalogueAction {
  readonly key: PermissionKey
  /** The role grid's column name (kit 40.3 rule 10). */
  readonly short: string
  readonly label: string
  readonly needs: readonly CatalogueNeed[]
}

export interface CatalogueSection {
  readonly key: string
  readonly label: string
  /** The scopes the role grid offers for this section (kit 40.4 rule 3). */
  readonly scopes: readonly Scope[]
  /** This section's Pick key, when it has one. */
  readonly pick: PermissionKey | null
  /** Every active user holds this Pick at All; the screens never mention it. */
  readonly pickForEveryone: boolean
  readonly actions: readonly CatalogueAction[]
}

export interface CatalogueModule {
  readonly key: ModuleKey
  readonly label: string
  /** Shown only on Admin's read-only role editor (kit 40.3 rule 13). */
  readonly adminOnly: boolean
  readonly seeAmounts: { readonly key: PermissionKey; readonly label: string } | null
  readonly sections: readonly CatalogueSection[]
}

/** Modules, sections and actions in catalogue order, for the role editor. */
export const CATALOGUE: readonly CatalogueModule[] = [
  {
    key: 'budget',
    label: 'Budget',
    adminOnly: false,
    seeAmounts: {
      key: 'budget.amounts.see',
      label: 'see amounts (cost, budgets)',
    },
    sections: [
      {
        key: 'projects',
        label: 'Projects',
        scopes: ['own', 'team', 'units', 'all'],
        pick: 'budget.projects.pick',
        pickForEveryone: false,
        actions: [
          {
            key: 'budget.projects.view',
            short: 'View',
            label: 'view projects',
            needs: [],
          },
          {
            key: 'budget.projects.create',
            short: 'Add',
            label: 'add projects',
            needs: [
              {
                pick: 'budget.sites.pick',
                scope: 'same',
              },
            ],
          },
          {
            key: 'budget.projects.edit',
            short: 'Edit',
            label: 'edit projects',
            needs: [
              {
                pick: 'budget.sites.pick',
                scope: 'same',
              },
            ],
          },
          {
            key: 'budget.projects.delete',
            short: 'Delete',
            label: 'delete projects',
            needs: [],
          },
        ],
      },
      {
        key: 'sites',
        label: 'Sites',
        scopes: ['own', 'team', 'units', 'all'],
        pick: 'budget.sites.pick',
        pickForEveryone: false,
        actions: [
          {
            key: 'budget.sites.view',
            short: 'View',
            label: 'view sites',
            needs: [
              {
                pick: 'budget.projects.pick',
                scope: 'same',
              },
            ],
          },
          {
            key: 'budget.sites.create',
            short: 'Add',
            label: 'add sites',
            needs: [
              {
                pick: 'budget.projects.pick',
                scope: 'same',
              },
            ],
          },
          {
            key: 'budget.sites.edit',
            short: 'Edit',
            label: 'edit sites',
            needs: [
              {
                pick: 'budget.projects.pick',
                scope: 'same',
              },
            ],
          },
          {
            key: 'budget.sites.change_people',
            short: 'Change people',
            label: 'change a site\'s manager or supervisor',
            needs: [
              {
                pick: 'platform.people.pick',
                scope: 'all',
              },
            ],
          },
          {
            key: 'budget.sites.delete',
            short: 'Delete',
            label: 'delete sites',
            needs: [],
          },
        ],
      },
      {
        key: 'budgets',
        label: 'Budgets',
        scopes: ['own', 'team', 'units', 'all'],
        pick: null,
        pickForEveryone: false,
        actions: [
          {
            key: 'budget.budgets.view',
            short: 'View',
            label: 'view budgets',
            needs: [
              {
                amounts: 'budget.amounts.see',
              },
            ],
          },
          {
            key: 'budget.budgets.edit',
            short: 'Edit',
            label: 'edit budgets',
            needs: [
              {
                amounts: 'budget.amounts.see',
              },
            ],
          },
        ],
      },
      {
        key: 'expenses',
        label: 'Expenses',
        scopes: ['own', 'team', 'units', 'all'],
        pick: null,
        pickForEveryone: false,
        actions: [
          {
            key: 'budget.expenses.view',
            short: 'View',
            label: 'view expenses',
            needs: [
              {
                pick: 'budget.sites.pick',
                scope: 'same',
              },
              {
                pick: 'budget.projects.pick',
                scope: 'same',
              },
            ],
          },
          {
            key: 'budget.expenses.create',
            short: 'Add',
            label: 'add expenses',
            needs: [
              {
                pick: 'budget.sites.pick',
                scope: 'same',
              },
              {
                amounts: 'budget.amounts.see',
              },
            ],
          },
          {
            key: 'budget.expenses.edit',
            short: 'Edit',
            label: 'edit expenses',
            needs: [
              {
                pick: 'budget.sites.pick',
                scope: 'same',
              },
              {
                amounts: 'budget.amounts.see',
              },
            ],
          },
          {
            key: 'budget.expenses.delete',
            short: 'Delete',
            label: 'delete expenses',
            needs: [],
          },
        ],
      },
      {
        key: 'cost_heads',
        label: 'Cost heads',
        scopes: ['all'],
        pick: 'budget.cost_heads.pick',
        pickForEveryone: true,
        actions: [
          {
            key: 'budget.cost_heads.manage',
            short: 'Manage',
            label: 'manage cost heads',
            needs: [],
          },
        ],
      },
      {
        key: 'reports',
        label: 'Reports',
        scopes: ['own', 'team', 'units', 'all'],
        pick: null,
        pickForEveryone: false,
        actions: [
          {
            key: 'budget.reports.view',
            short: 'View',
            label: 'view reports',
            needs: [
              {
                amounts: 'budget.amounts.see',
              },
              {
                pick: 'budget.sites.pick',
                scope: 'same',
              },
              {
                pick: 'budget.projects.pick',
                scope: 'same',
              },
              {
                pick: 'platform.people.pick',
                scope: 'same',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    key: 'complaints',
    label: 'Complaints',
    adminOnly: false,
    seeAmounts: null,
    sections: [
      {
        key: 'complaints',
        label: 'Complaints',
        scopes: ['own', 'team', 'units', 'all'],
        pick: null,
        pickForEveryone: false,
        actions: [
          {
            key: 'complaints.complaints.view',
            short: 'View',
            label: 'view complaints',
            needs: [],
          },
          {
            key: 'complaints.complaints.raise',
            short: 'Raise',
            label: 'raise complaints',
            needs: [
              {
                pick: 'budget.sites.pick',
                scope: 'all',
              },
            ],
          },
          {
            key: 'complaints.complaints.comment',
            short: 'Comment',
            label: 'comment on complaints',
            needs: [],
          },
          {
            key: 'complaints.complaints.work',
            short: 'Work',
            label: 'start and resolve complaints assigned to them',
            needs: [],
          },
          {
            key: 'complaints.complaints.approve',
            short: 'Approve',
            label: 'approve or send back complaints',
            needs: [],
          },
          {
            key: 'complaints.complaints.reassign',
            short: 'Reassign',
            label: 'reassign complaints',
            needs: [
              {
                pick: 'platform.people.pick',
                scope: 'all',
              },
            ],
          },
        ],
      },
      {
        key: 'categories',
        label: 'Categories',
        scopes: ['all'],
        pick: 'complaints.categories.pick',
        pickForEveryone: true,
        actions: [
          {
            key: 'complaints.categories.manage',
            short: 'Manage',
            label: 'manage complaint categories',
            needs: [],
          },
        ],
      },
    ],
  },
  {
    key: 'platform',
    label: 'Settings',
    adminOnly: false,
    seeAmounts: null,
    sections: [
      {
        key: 'people',
        label: 'People',
        scopes: ['own', 'team', 'units', 'all'],
        pick: 'platform.people.pick',
        pickForEveryone: false,
        actions: [
          {
            key: 'platform.people.view',
            short: 'View',
            label: 'view people',
            needs: [],
          },
          {
            key: 'platform.people.create',
            short: 'Add',
            label: 'add people',
            needs: [],
          },
          {
            key: 'platform.people.edit',
            short: 'Edit',
            label: 'edit people',
            needs: [],
          },
          {
            key: 'platform.people.delete',
            short: 'Delete',
            label: 'delete people',
            needs: [],
          },
        ],
      },
      {
        key: 'designations',
        label: 'Designations',
        scopes: ['all'],
        pick: 'platform.designations.pick',
        pickForEveryone: true,
        actions: [
          {
            key: 'platform.designations.manage',
            short: 'Manage',
            label: 'manage designations',
            needs: [],
          },
        ],
      },
      {
        key: 'locations',
        label: 'Locations',
        scopes: ['all'],
        pick: 'platform.locations.pick',
        pickForEveryone: true,
        actions: [
          {
            key: 'platform.locations.manage',
            short: 'Manage',
            label: 'manage locations',
            needs: [],
          },
        ],
      },
    ],
  },
  {
    key: 'access',
    label: 'Access',
    adminOnly: true,
    seeAmounts: null,
    sections: [
      {
        key: 'rights',
        label: 'Access',
        scopes: ['all'],
        pick: null,
        pickForEveryone: false,
        actions: [
          {
            key: 'access.rights.manage',
            short: 'Manage',
            label: 'manage roles and people\'s access',
            needs: [],
          },
        ],
      },
    ],
  },
]
